# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61305feaa4c9695342601dfc6d0cb958e1f508633935b284c90cf629e78c374359f521209cb3edede23e301776208f1e670f2479c607402a7b20d21fb723d76c

test:
  secret_key_base: 8fa16a885ab66b5d2d8908fa43e1d8f0e6810d639f0e775550962f618630075726607b303ad8a8bf63bd8a7827553b3fa604534ab6295ccc0222ae5f77415062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
